### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address [help] 

### ISSUE THREAD

**Issue by Alanzimm1985** [OWASP/QRLJacking#148] opened 2021-06-02 20:54 UTC
<odule(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]                                                            
[+] Initializing webserver... [whatsapp]

<odule(grabber/whatsapp) > 
[+] Got session on whatsapp module
[+] Session saved successfully
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alanzimm85/Desktop/QRLJacking/QRLJacker/core/browser.py", line 170, in serve_module
    webserver.start_serving(host)
  File "/home/alanzimm85/Desktop/QRLJacking/QRLJacker/core/module_utils.py", line 32, in start_serving
    self.httpd = ReusableTCPServer( (host, self.port), MyHandler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

**Comment by melbadry9** [comment] 2021-06-07 15:14
This is a duplicate of #131

**Closed by melbadry9** 2021-06-07 15:14 UTC
Labels: duplicate
