### ISSUE TITLE
this tool is not working

### ISSUE THREAD

**Issue by azamet90** [OWASP/QRLJacking#68] opened 2019-11-18 07:48 UTC
i open firefox as normal user and trying to open the tool as normal user i get permission denied on qrljacking

if i open firefox normal user qrljacking superuser then i get that error which everybody gets!
my firefox is up to date everything is up to date but i think the tool is not up to date?

**Comment by D4Vinci** [comment] 2019-11-23 17:53
This is a duplicate of #37 
It's not a problem from QRLJacker

**Closed by D4Vinci** 2019-11-23 17:53 UTC
Labels: duplicate, invalid
