### ISSUE TITLE
no sessions captured

### ISSUE THREAD

**Issue by john-whick-13** [OWASP/QRLJacking#206] opened 2023-04-12 20:45 UTC
after running the tool , every thing running well , i git the QR code , scan it by whatsapp , but canr catch the sessions , i used python3.7 on kali linux last version

Linux kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1kali1 (2023-03-22) x86_64 GNU/Linux
Python 3.7.6

QrlJacker > use grabber/whatsapp

QrlJacker Module(grabber/whatsapp) > set port 1337
[+] port => 1337

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) >

**Comment by LucaReggiannini** [comment] 2023-04-13 14:51
Try using the "Debug" command before "run": you should see an additional Firefox instance opening with the real WhatsApp page. Now open _another_ Firefox instance on localhost:1337 and scan the QR code. What happens on the other Firefox? Do you see the the WhatsApp web session opening or does it remain on the Qr page?

**Comment by john-whick-13** [comment] 2023-04-13 16:06
i follow the steps , the other firefox instance open the session , and logedin to my whatsapp ,  but still recieved no session captured on the tool

**Comment by LucaReggiannini** [comment] 2023-04-13 16:25
With "debug" mode is there any new message other than what you posted in the first message? Can you provide a screenshot of the terminal and the two WhatsApp session _after_ you scan the code?

**Comment by john-whick-13** [comment] 2023-04-13 16:52
no other messages in debug mode , kindly find the attached photos


![Screenshot_2023-04-13_12_47_31](https://user-images.githubusercontent.com/129062899/231829952-a6b107ce-0c79-4874-9afd-7740a5295a03.png)
![Screenshot_2023-04-13_12_48_40](https://user-images.githubusercontent.com/129062899/231829978-1e8ef51f-542e-496c-9ce2-ef3f797844be.png) 
![whatsapp](https://user-images.githubusercontent.com/129062899/231829985-62eee4af-efea-4a4c-ad43-448bfdf0f329.jpg)

**Comment by LucaReggiannini** [comment] 2023-04-13 19:38
Thanks for the info.
Unfortunately i can't reproduce the problem with the same setup:
![Screenshot from 2023-04-13 21-08-58](https://user-images.githubusercontent.com/46603573/231860164-7d3575a8-0d75-428b-a0e8-3c2786152621.png)

For me the code is working correcly.
I can suggest you to do the following: 
- repeat the steps you already did
- when you are inside Whatsapp web on the Selenium Firefox instance, go to **Menu -> More tools -> Web Developer Tools**
- go to "**console**" tab and enter the following:
`$x("/html/body/div[1]/div/div/div[4]/header/div[1]/div/img")`

This code will check if the element with the given XPath exists in the page.
If exists, you should see something like this:
![Screenshot from 2023-04-13 21-24-46](https://user-images.githubusercontent.com/46603573/231864945-1061d0b9-6f85-4f19-aa10-97fa4da5f6e9.png)

if not you should see just the following message:
`Array []`

in the latter case please try the following:
- Right Click on your Whatsapp Avatar Image (upper left in the page) and click "**inspect**"
- on the highlighted code **right click -> copy -> Xpath** and write here your XPath

**Comment by john-whick-13** [comment] 2023-04-13 21:51
i follow your step and got empty array like this  =====> Array []

here the XPath === 
/html/body/div[1]/div/div/div[3]/div[1]/span/div/span/div/div/div[1]/div/div/span/div

**Comment by LucaReggiannini** [comment] 2023-04-15 00:33
I'm still not able to reproduce the issue: i tried different browser, different system, different languages and different localisations but the XPath for me remains `/html/body/div[1]/div/div/div[4]/header/div[1]/div/img` in every test.

As a workaround, i can suggest to change the value of `change_identifier` variable inside **QRLJacker/core/modules/grabber/whatsapp.py** and put your XPath. Variable `change_identifier` must contain the XPath of an element that is present **only** on the chat web page (not in the QRCode page): when QRLJacker detects this Xpath it means that you went from the page with the QRCode to the chat page (this means you have a valid session).

If you want to dig more you can try different setups as i did (different browser, system, languages...), check if everything is installed correctly on your system, try different python versions (personally i use the last release).
What code do you have for the avatar image? See the `<img>` tag in my page:

![Screenshot from 2023-04-14 00-56-44](https://user-images.githubusercontent.com/46603573/232174222-6900d2be-e5d7-4442-b23a-61424f9f4e11.png)

**Comment by john-whick-13** [comment] 2023-04-15 12:49
thanks for your kindly interest and i really appreciate your support 

i changed xpath to    change_identifier = '/html/body/div[1]/div/div/div[4]/header/div[1]/div/div/span'

then it work m i can catch the session but , the QRCode dissapear , and not appear any more 
![Screenshot_2023-04-15_08_42_14](https://user-images.githubusercontent.com/129062899/232224577-6c250329-745d-4a13-8499-98ccaf93b816.png)
![Screenshot_2023-04-15_08_43_14](https://user-images.githubusercontent.com/129062899/232224581-18e3b0e5-60e4-4c36-8011-364650160d8d.png)

**Comment by LucaReggiannini** [comment] 2023-04-15 14:24
This is normal: the session is saved and the Selenium Firefox is closed (so you don't have the QR Code on the Phishing page anymore; maybe i will propose a change to make it stealthier). Once you have the session use `sessions -l `and `sessions -i `to interact with a specific session. I think this issue can be closed

**Comment by john-whick-13** [comment] 2023-04-16 08:27
thanks alot , really thanks , one more reques please , how can i use this tool over wan

**Comment by john-whick-13** [comment] 2023-04-16 12:46
i can make port forwarding , but i talk about QRLJacking tool configuration , what should i do

**Comment by LucaReggiannini** [comment] 2023-04-16 13:20
Well... nothing: when you use `set port 1337` the framework will open a listening port on 0.0.0.0:1337. This address will serve the Web Server with the Phishing page. Address 0.0.0.0 means "any interface" on your machine. So you have to take your local interface IP address (with`ifconfig`, `ip addr` or any other tool you use on your machine) and forward public port 1337 to internal port 1337 on that local address. When make a connection to _your-public-ip:1337_ the router will forward the connection to _your-local-ip:1337_ and you will see the Phishing page. But i think this is beyond the scope of this issue :sweat_smile:

**Comment by john-whick-13** [comment] 2023-04-16 15:11
thanks alot it work now very well , one more think if i want to modify the QRL page m what should i do 

really thanks for your kindly interest 😅😅😅😅😅😅

**Comment by LucaReggiannini** [comment] 2023-04-16 15:20
As the page itself suggest, just modify _QRLJacking/QRLJacker/core/templates/phishing_page.html_ file with your own code. Please if the original problem is solved, close the issue

**Comment by john-whick-13** [comment] 2023-04-16 15:27
can i modify it with flutter not html , is it possible or i should use html only

**Closed** 2023-04-16 15:44 UTC

**Comment by dr1408** [comment] 2024-01-17 22:44
Thanks alot I solve the sessions not captured by this demonstration I changed the identifier and boom works but the identifier is different than what is here

**Comment by dr1408** [comment] 2024-01-18 00:10
I use it with android phone and xfce and vncviewer so it open firfox in vnc and when i enter any conversation it crashes and exit .. any workout for the crashes or can i open it with my mobile browser and how ?

**Comment by dr1408** [comment] 2024-01-18 04:02
@LucaReggiannini  this is the geckodriver tracback

Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=80.6358) Exiting due to channel error.
Exiting due to channel error.
[1705551185835](tel:1705551185835)   geckodriver     INFO    Listening on 127.0.0.1:39869
[1705551195254](tel:1705551195254)   mozrunner::runner       INFO    Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/dat ... 46607" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/data/data/com.termux/files/>
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
[1705551197478](tel:1705551197478)   Marionette      INFO    Marionette enabled
Read port: 39865
Read port: 39865
[1705551197732](tel:1705551197732)   Marionette      INFO    Listening on port 36577
Read port: 36577
WebDriver BiDi listening on ws://127.0.0.1:46607
[1705551198233](tel:1705551198233)   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
console.error: ({})
console.error: "Translations: SIMD not supported" (new CompileError("at offset 15: bad type", "chrome://global/content/translations/simd-detect-worker.js", 14))
DevTools listening on ws://127.0.0.1:46607/devtools/browser/a45657dd-1c54-44ff-ba84-056b9b8dd960
JavaScript warning: https://web.whatsapp.com/main.0cf917fc9b3d8f353e54.js, line 5: unreachable code after return statement
JavaScript warning: https://web.whatsapp.com/main.0cf917fc9b3d8f353e54.js, line 5: unreachable code after return statement
JavaScript error: resource://gre/modules/PromiseWorker.sys.mjs, line 102: Error: Could not get children of file(/data/data/com.termux/files/usr/tmp/rust_mozprofileSvOYg0/thumbnails) because it does not exist
Exiting due to channel error.
Exiting due to channel error.

**Comment by dr1408** [comment] 2024-01-18 06:41
I dont have rust package installed do i need to install it manually ?
